name: myapp
description: "Flutter demos"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.3
  line_icons: ^2.0.3
  flutter_zoom_drawer: ^3.2.0
  flutter_expandable_table: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/daynight/
    - assets/advanced_drawer/